apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ignition-payload-server
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hypershift.openshift.io
  resources:
  - ignitionpayloads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hypershift.openshift.io
  resources:
  - ignitionpayloads/status
  verbs:
  - get
  - list
  - watch
  - patch
  - update
