apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ignition-payload-server
spec:
  host: ""
  tls:
    insecureEdgeTerminationPolicy: None
    termination: passthrough
  to:
    kind: Service
    name: ignition-payload-server-proxy
  wildcardPolicy: None
