apiVersion: v1
kind: Service
metadata:
  name: ignition-payload-server-proxy
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: ignition-payload-server-proxy
  type: ClusterIP
