apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    hypershift.openshift.io/managed-by: control-plane-operator
  name: cluster-autoscaler
  namespace: HCP_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-autoscaler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        hypershift.openshift.io/release-image: registry.build09.ci.openshift.org/ci-op-vxb10zc4/release@sha256:3e5e66b7bb62b2e3c4c80bd1a976cfb618abe99356fc75d754a1e042afd25d25
      labels:
        app: cluster-autoscaler
        hypershift.openshift.io/control-plane-component: cluster-autoscaler
        hypershift.openshift.io/hosted-control-plane: e2e-clusters-9vwbx-example-wzssw
        hypershift.openshift.io/need-management-kas-access: "true"
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: hypershift.openshift.io/control-plane
                operator: In
                values:
                - "true"
            weight: 50
          - preference:
              matchExpressions:
              - key: hypershift.openshift.io/cluster
                operator: In
                values:
                - e2e-clusters-9vwbx-example-wzssw
            weight: 100
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  hypershift.openshift.io/hosted-control-plane: e2e-clusters-9vwbx-example-wzssw
              topologyKey: kubernetes.io/hostname
            weight: 100
      automountServiceAccountToken: true
      containers:
      - args:
        - --expander=priority,least-waste
        - --cloud-provider=clusterapi
        - --node-group-auto-discovery=clusterapi:namespace=$(MY_NAMESPACE)
        - --kubeconfig=/mnt/kubeconfig/target-kubeconfig
        - --clusterapi-cloud-config-authoritative
        - --skip-nodes-with-local-storage=false
        - --alsologtostderr
        - --leader-elect-lease-duration=137s
        - --leader-elect-retry-period=26s
        - --leader-elect-renew-deadline=107s
        - --balance-similar-node-groups=true
        - --v=4
        - --balancing-ignore-label=hypershift.openshift.io/nodePool
        - --balancing-ignore-label=topology.ebs.csi.aws.com/zone
        - --balancing-ignore-label=topology.disk.csi.azure.com/zone
        - --balancing-ignore-label=ibm-cloud.kubernetes.io/worker-id
        - --balancing-ignore-label=vpc-block-csi-driver-labels
        command:
        - /usr/bin/cluster-autoscaler
        env:
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: registry.build09.ci.openshift.org/ci-op-vxb10zc4/stable@sha256:60d5133df9b38b86d16ac2059ac284a03ae2f6e42343df59c1a8ec009faa1c25
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health-check
            port: 8085
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 5
        name: cluster-autoscaler
        ports:
        - containerPort: 8085
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health-check
            port: 8085
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 10m
            memory: 60Mi
        volumeMounts:
        - mountPath: /mnt/kubeconfig
          name: kubeconfig
      initContainers:
      - command:
        - /usr/bin/control-plane-operator
        - availability-prober
        - --target
        - https://kube-apiserver:6443/readyz
        image: registry.build09.ci.openshift.org/ci-op-vxb10zc4/stable@sha256:7c0c93890233b202656d5a64f0d5f9879fbac6084d4e8185b706a8fb945472ec
        imagePullPolicy: IfNotPresent
        name: availability-prober
        resources: {}
      priorityClassName: hypershift-control-plane
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: cluster-autoscaler
      serviceAccountName: cluster-autoscaler
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: hypershift.openshift.io/control-plane
        operator: Equal
        value: "true"
      - effect: NoSchedule
        key: hypershift.openshift.io/cluster
        operator: Equal
        value: e2e-clusters-9vwbx-example-wzssw
      volumes:
      - name: kubeconfig
        secret:
          defaultMode: 416
          items:
          - key: value
            path: target-kubeconfig
          secretName: example-wzssw-kubeconfig
