//go:build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSCloudProviderConfig) DeepCopyInto(out *AWSCloudProviderConfig) {
	*out = *in
	if in.Subnet != nil {
		in, out := &in.Subnet, &out.Subnet
		*out = new(AWSResourceReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSCloudProviderConfig.
func (in *AWSCloudProviderConfig) DeepCopy() *AWSCloudProviderConfig {
	if in == nil {
		return nil
	}
	out := new(AWSCloudProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSResourceReference) DeepCopyInto(out *AWSResourceReference) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]Filter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSResourceReference.
func (in *AWSResourceReference) DeepCopy() *AWSResourceReference {
	if in == nil {
		return nil
	}
	out := new(AWSResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSResourceTag) DeepCopyInto(out *AWSResourceTag) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSResourceTag.
func (in *AWSResourceTag) DeepCopy() *AWSResourceTag {
	if in == nil {
		return nil
	}
	out := new(AWSResourceTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSRolesRef) DeepCopyInto(out *AWSRolesRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSRolesRef.
func (in *AWSRolesRef) DeepCopy() *AWSRolesRef {
	if in == nil {
		return nil
	}
	out := new(AWSRolesRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSServiceEndpoint) DeepCopyInto(out *AWSServiceEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSServiceEndpoint.
func (in *AWSServiceEndpoint) DeepCopy() *AWSServiceEndpoint {
	if in == nil {
		return nil
	}
	out := new(AWSServiceEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSharedVPC) DeepCopyInto(out *AWSSharedVPC) {
	*out = *in
	out.RolesRef = in.RolesRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSharedVPC.
func (in *AWSSharedVPC) DeepCopy() *AWSSharedVPC {
	if in == nil {
		return nil
	}
	out := new(AWSSharedVPC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSharedVPCRolesRef) DeepCopyInto(out *AWSSharedVPCRolesRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSharedVPCRolesRef.
func (in *AWSSharedVPCRolesRef) DeepCopy() *AWSSharedVPCRolesRef {
	if in == nil {
		return nil
	}
	out := new(AWSSharedVPCRolesRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Filter) DeepCopyInto(out *Filter) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Filter.
func (in *Filter) DeepCopy() *Filter {
	if in == nil {
		return nil
	}
	out := new(Filter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedAWSCluster) DeepCopyInto(out *HostedAWSCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedAWSCluster.
func (in *HostedAWSCluster) DeepCopy() *HostedAWSCluster {
	if in == nil {
		return nil
	}
	out := new(HostedAWSCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostedAWSCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedAWSClusterList) DeepCopyInto(out *HostedAWSClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HostedAWSCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedAWSClusterList.
func (in *HostedAWSClusterList) DeepCopy() *HostedAWSClusterList {
	if in == nil {
		return nil
	}
	out := new(HostedAWSClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostedAWSClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedAWSClusterSpec) DeepCopyInto(out *HostedAWSClusterSpec) {
	*out = *in
	if in.CloudProviderConfig != nil {
		in, out := &in.CloudProviderConfig, &out.CloudProviderConfig
		*out = new(AWSCloudProviderConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceEndpoints != nil {
		in, out := &in.ServiceEndpoints, &out.ServiceEndpoints
		*out = make([]AWSServiceEndpoint, len(*in))
		copy(*out, *in)
	}
	out.RolesRef = in.RolesRef
	if in.ResourceTags != nil {
		in, out := &in.ResourceTags, &out.ResourceTags
		*out = make([]AWSResourceTag, len(*in))
		copy(*out, *in)
	}
	if in.AdditionalAllowedPrincipals != nil {
		in, out := &in.AdditionalAllowedPrincipals, &out.AdditionalAllowedPrincipals
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SharedVPC != nil {
		in, out := &in.SharedVPC, &out.SharedVPC
		*out = new(AWSSharedVPC)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedAWSClusterSpec.
func (in *HostedAWSClusterSpec) DeepCopy() *HostedAWSClusterSpec {
	if in == nil {
		return nil
	}
	out := new(HostedAWSClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedAWSClusterStatus) DeepCopyInto(out *HostedAWSClusterStatus) {
	*out = *in
	if in.InfrastructureCRRef != nil {
		in, out := &in.InfrastructureCRRef, &out.InfrastructureCRRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedAWSClusterStatus.
func (in *HostedAWSClusterStatus) DeepCopy() *HostedAWSClusterStatus {
	if in == nil {
		return nil
	}
	out := new(HostedAWSClusterStatus)
	in.DeepCopyInto(out)
	return out
}
